services:
  grafana:
    container_name: 'harper-grafana-datasource'

    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-12.1.1}
    volumes:
      - ./dist:/var/lib/grafana/plugins/harper-datasource
      - .:/root/harper-datasource

    networks:
      - grafana-harper
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

  harper:
    image: harpersystems/harper:4.6.11
    build:
      context: ../harper-main
      dockerfile: ../harper-main/utility/dev/Dockerfile
    container_name: 'gds-harper'
    user: root
    volumes:
      - ./hdb:/home/harper/hdb
    networks:
      - grafana-harper
    ports:
      - '49925:9925'
      - '49926:9926'
    environment:
      HDB_ADMIN_USERNAME: admin
      HDB_ADMIN_PASSWORD: foobarbaz
      LOGGING_LEVEL: trace

networks:
  grafana-harper:
