services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-12.3.1}
    volumes:
      - ./dist:/var/lib/grafana/plugins/harper-datasource
      - .:/root/harper-datasource
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

