services:
  grafana:
    user: root
    container_name: 'harper-grafana-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.6.1}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/harper-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/harper-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.harper-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: harper-datasource

    networks:
      - grafana-harper

  harper:
    image: harpersystems/harper:4.6.0-alpha.1
    container_name: 'gds-harper'
    user: root
    volumes:
      - ./hdb:/home/harper/hdb
    networks:
      - grafana-harper
    ports:
      - '49925:9925'
      - '49926:9926'
    environment:
      HDB_ADMIN_USERNAME: admin
      HDB_ADMIN_PASSWORD: foobarbaz
      LOGGING_LEVEL: trace

networks:
  grafana-harper:
